// =============================================================
//  Word Garden - secret word list
//  The game picks one of these at random.
//  To add a word: lowercase, exactly 5 letters, in quotes, then a comma.
//  Keep them friendly, everyday words.
// =============================================================

const WORDS = [
  "about", "above", "actor", "adult", "after", "again", "agree", "alarm",
  "album", "alive", "allow", "alone", "along", "angel", "anger", "angle",
  "angry", "ankle", "apple", "apron", "arena", "arise", "arrow", "aside",
  "attic", "award", "aware",
  "bacon", "badge", "baker", "basic", "basin", "beach", "beard", "beast",
  "begin", "being", "bells", "bench", "berry", "birds", "birth", "black",
  "blade", "blame", "blank", "blend", "bless", "blind", "block", "bloom",
  "board", "boast", "boots", "brain", "brave", "bread", "break", "brick",
  "bride", "brief", "bring", "brook", "brush", "build", "bunny",
  "cabin", "cable", "candy", "canoe", "cards", "cargo", "carry", "catch",
  "cause", "chain", "chair", "charm", "chart", "cheek", "cheer", "chess",
  "chest", "chick", "chief", "child", "chime", "china", "choir", "chord",
  "cider", "cinch", "claim", "class", "clean", "clear", "clerk", "cliff",
  "climb", "clock", "close", "cloth", "cloud", "clown", "coach", "coast",
  "cocoa", "color", "comet", "coral", "couch", "count", "cover", "crane",
  "cream", "creek", "crisp", "crown", "crumb", "crust",
  "daily", "dairy", "daisy", "dance", "delay", "diary", "dream", "dress",
  "drink", "drive",
  "eagle", "early", "earth", "eight", "elbow", "empty", "enjoy", "entry",
  "equal", "event", "extra",
  "fable", "faith", "fancy", "feast", "fence", "field", "flame", "flash",
  "fleet", "float", "flock", "flood", "floor", "flour", "fluff", "focus",
  "forty", "frame", "fresh", "front", "frost", "fruit", "funny",
  "geese", "ghost", "giant", "given", "glass", "globe", "glove", "grace",
  "grain", "grand", "grape", "grass", "gravy", "great", "green", "greet",
  "grill", "group", "guard", "guess", "guest", "guide",
  "habit", "happy", "heart", "heavy", "hedge", "hello", "honey", "horse",
  "hotel", "house", "human", "humor",
  "ideas", "image", "inner",
  "jelly", "jewel", "joint", "jolly", "juice",
  "kayak", "kitty", "knife", "knock",
  "label", "lemon", "level", "light", "lilac", "linen", "lunch",
  "magic", "maple", "march", "match", "mayor", "meals", "melon", "merry",
  "metal", "minor", "mirth", "model", "money", "month", "motor", "mouse",
  "mouth", "movie", "music",
  "nanny", "nerve", "never", "night", "noble", "noise", "north", "novel",
  "nurse",
  "ocean", "offer", "olive", "onion", "opera", "orbit", "order", "otter",
  "outer", "owner",
  "paint", "panel", "paper", "party", "pasta", "patch", "peace", "peach",
  "pearl", "pecan", "penny", "piano", "piece", "pilot", "pizza", "place",
  "plain", "plane", "plant", "plate", "plaza", "plush", "poems", "point",
  "polka", "porch", "pound", "power", "press", "price", "pride", "prize",
  "proud", "puppy",
  "quack", "queen", "quiet", "quilt",
  "radio", "rainy", "raise", "ranch", "reach", "ready", "relax", "river",
  "roast", "robin", "rocky", "roses", "round", "royal", "ruler",
  "sauce", "scale", "scarf", "scene", "scone", "scout", "shade", "shake",
  "share", "sheep", "shelf", "shell", "shine", "shirt", "shore", "short",
  "shout", "sight", "skate", "skirt", "sleep", "slice", "smile", "smoke",
  "snack", "snail", "snake", "snowy", "socks", "solar", "sound", "south",
  "space", "spare", "spark", "speak", "spice", "spoon", "sport", "spray",
  "squad", "stage", "stair", "stamp", "stand", "stars", "start", "steam",
  "steel", "stick", "stone", "stool", "storm", "story", "stove", "straw",
  "sugar", "sunny", "super", "swans", "sweet", "swing",
  "table", "tasty", "teach", "teeth", "thank", "theme", "thick", "thing",
  "think", "three", "throw", "thumb", "tiger", "toast", "today", "torch",
  "towel", "tower", "trace", "track", "trail", "train", "treat", "trees",
  "trend", "trick", "truck", "trunk", "trust", "truth", "tulip", "tutor",
  "uncle", "under", "unity",
  "value", "video", "visit", "voice",
  "wagon", "waltz", "watch", "water", "whale", "wheat", "wheel", "white",
  "whole", "woman", "world", "worry", "write",
  "yacht", "yeast", "young", "youth",
  "zebra",
];
