// =============================================================
//  Word Garden - secret word lists
//  The game picks one at random from the list for the length chosen
//  (4, 5 or 6 letters, or Mix for any of them).
//  To add a word: lowercase, the right number of letters, in quotes,
//  then a comma. Keep them friendly, everyday words.
//  A word in the wrong list (wrong length) is quietly skipped.
// =============================================================

const WORDS = {
  4: [
    "able", "acre", "aunt", "baby", "back", "bake", "ball", "band", "bank", "bark",
    "barn", "bath", "bead", "beak", "beam", "bean", "bear", "beef", "bell", "belt",
    "bend", "best", "bike", "bird", "bite", "blue", "boat", "body", "bone", "book",
    "boot", "bowl", "bush", "cake", "calm", "camp", "cane", "card", "care", "cart",
    "cash", "cave", "chef", "city", "clay", "coat", "code", "coin", "cold", "cook",
    "cool", "copy", "corn", "cozy", "crab", "crib", "crop", "cube", "cups", "cure",
    "cute", "dark", "date", "dawn", "deer", "desk", "dime", "dish", "dock", "doll",
    "door", "dove", "down", "duck", "dusk", "east", "easy", "echo", "edge", "farm",
    "fawn", "fern", "fish", "flag", "fond", "food", "foot", "fork", "free", "frog",
    "fuel", "game", "gift", "glad", "glow", "goat", "gold", "golf", "good", "gown",
    "gray", "grin", "hair", "half", "hall", "hand", "harp", "hats", "hawk", "heal",
    "heat", "herb", "hike", "hill", "hive", "home", "honk", "hood", "hope", "horn",
    "hose", "host", "hour", "hymn", "idea", "inch", "iron", "jams", "jazz", "joke",
    "jump", "keep", "kind", "king", "kite", "knit", "lace", "lake", "lamb", "lamp",
    "land", "lawn", "leaf", "lily", "lime", "list", "loaf", "love", "lump", "mail",
    "malt", "maps", "mask", "meal", "milk", "mint", "mist", "mitt", "moon", "moss",
    "nest", "news", "nice", "noon", "note", "oats", "open", "oven", "pace", "page",
    "pail", "pair", "palm", "park", "path", "peak", "pear", "peas", "pine", "pink",
    "plum", "poem", "pond", "pony", "pool", "pots", "puff", "rain", "rake", "read",
    "rest", "rice", "road", "robe", "rock", "roof", "room", "rope", "rose", "ruby",
    "rugs", "safe", "sail", "salt", "sand", "seal", "seed", "shoe", "silk", "sing",
    "sink", "skip", "snow", "soap", "sock", "sofa", "soil", "song", "soup", "star",
    "stem", "stew", "swan", "swim", "tale", "tall", "tart", "team", "tent", "tide",
    "toad", "toes", "tour", "town", "tree", "tuna", "vase", "vest", "view", "vine",
    "walk", "warm", "wave", "wind", "wing", "wish", "wood", "wool", "yard", "yarn",
    "year", "zero",
  ],

  5: [
    "about", "above", "actor", "adult", "after", "again", "agree", "alarm", "album", "alive",
    "allow", "alone", "along", "angel", "anger", "angle", "angry", "ankle", "apple", "apron",
    "arena", "arise", "arrow", "aside", "attic", "award", "aware", "bacon", "badge", "baker",
    "basic", "basin", "beach", "beard", "beast", "begin", "being", "bells", "bench", "berry",
    "birds", "birth", "black", "blade", "blame", "blank", "blend", "bless", "blind", "block",
    "bloom", "board", "boast", "boots", "brain", "brave", "bread", "break", "brick", "bride",
    "brief", "bring", "brook", "brush", "build", "bunny", "cabin", "cable", "candy", "canoe",
    "cards", "cargo", "carry", "catch", "cause", "chain", "chair", "charm", "chart", "cheek",
    "cheer", "chess", "chest", "chick", "chief", "child", "chime", "china", "choir", "chord",
    "cider", "cinch", "claim", "class", "clean", "clear", "clerk", "cliff", "climb", "clock",
    "close", "cloth", "cloud", "clown", "coach", "coast", "cocoa", "color", "comet", "coral",
    "couch", "count", "cover", "crane", "cream", "creek", "crisp", "crown", "crumb", "crust",
    "daily", "dairy", "daisy", "dance", "delay", "diary", "dream", "dress", "drink", "drive",
    "eagle", "early", "earth", "eight", "elbow", "empty", "enjoy", "entry", "equal", "event",
    "extra", "fable", "faith", "fancy", "feast", "fence", "field", "flame", "flash", "fleet",
    "float", "flock", "flood", "floor", "flour", "fluff", "focus", "forty", "frame", "fresh",
    "front", "frost", "fruit", "funny", "geese", "ghost", "giant", "given", "glass", "globe",
    "glove", "grace", "grain", "grand", "grape", "grass", "gravy", "great", "green", "greet",
    "grill", "group", "guard", "guess", "guest", "guide", "habit", "happy", "heart", "heavy",
    "hedge", "hello", "honey", "horse", "hotel", "house", "human", "humor", "ideas", "image",
    "inner", "jelly", "jewel", "joint", "jolly", "juice", "kayak", "kitty", "knife", "knock",
    "label", "lemon", "level", "light", "lilac", "linen", "lunch", "magic", "maple", "march",
    "match", "mayor", "meals", "melon", "merry", "metal", "minor", "mirth", "model", "money",
    "month", "motor", "mouse", "mouth", "movie", "music", "nanny", "nerve", "never", "night",
    "noble", "noise", "north", "novel", "nurse", "ocean", "offer", "olive", "onion", "opera",
    "orbit", "order", "otter", "outer", "owner", "paint", "panel", "paper", "party", "pasta",
    "patch", "peace", "peach", "pearl", "pecan", "penny", "piano", "piece", "pilot", "pizza",
    "place", "plain", "plane", "plant", "plate", "plaza", "plush", "poems", "point", "polka",
    "porch", "pound", "power", "press", "price", "pride", "prize", "proud", "puppy", "quack",
    "queen", "quiet", "quilt", "radio", "rainy", "raise", "ranch", "reach", "ready", "relax",
    "river", "roast", "robin", "rocky", "roses", "round", "royal", "ruler", "sauce", "scale",
    "scarf", "scene", "scone", "scout", "shade", "shake", "share", "sheep", "shelf", "shell",
    "shine", "shirt", "shore", "short", "shout", "sight", "skate", "skirt", "sleep", "slice",
    "smile", "smoke", "snack", "snail", "snake", "snowy", "socks", "solar", "sound", "south",
    "space", "spare", "spark", "speak", "spice", "spoon", "sport", "spray", "squad", "stage",
    "stair", "stamp", "stand", "stars", "start", "steam", "steel", "stick", "stone", "stool",
    "storm", "story", "stove", "straw", "sugar", "sunny", "super", "swans", "sweet", "swing",
    "table", "tasty", "teach", "teeth", "thank", "theme", "thick", "thing", "think", "three",
    "throw", "thumb", "tiger", "toast", "today", "torch", "towel", "tower", "trace", "track",
    "trail", "train", "treat", "trees", "trend", "trick", "truck", "trunk", "trust", "truth",
    "tulip", "tutor", "uncle", "under", "unity", "value", "video", "visit", "voice", "wagon",
    "waltz", "watch", "water", "whale", "wheat", "wheel", "white", "whole", "woman", "world",
    "worry", "write", "yacht", "yeast", "young", "youth", "zebra",
  ],

  6: [
    "almond", "animal", "answer", "anyone", "apples", "arrive", "artist", "autumn", "banana", "basket",
    "beauty", "before", "better", "bottle", "branch", "breeze", "bridge", "bright", "bubble", "bucket",
    "butter", "button", "candle", "carpet", "carrot", "castle", "cherry", "chores", "circle", "closet",
    "coffee", "cookie", "cotton", "county", "cousin", "cradle", "crayon", "cruise", "dinner", "doctor",
    "donkey", "dragon", "drawer", "easily", "eleven", "family", "farmer", "father", "finger", "flower",
    "forest", "friend", "frozen", "garage", "garden", "gentle", "ginger", "golden", "guitar", "hammer",
    "harbor", "heater", "helper", "hiking", "honest", "island", "jacket", "kettle", "kitten", "ladder",
    "laptop", "letter", "listen", "little", "lovely", "market", "meadow", "melody", "mirror", "mitten",
    "modern", "monkey", "mother", "muffin", "museum", "napkin", "needle", "number", "orange", "paddle",
    "pantry", "parade", "parrot", "pencil", "people", "pepper", "picnic", "pillow", "planet", "pocket",
    "potato", "puzzle", "rabbit", "radish", "record", "ribbon", "riddle", "rocket", "saddle", "sailor",
    "salmon", "school", "season", "silver", "simple", "singer", "sister", "smooth", "spring", "square",
    "stream", "street", "string", "summer", "sunday", "supper", "sweets", "tables", "tailor", "teapot",
    "thanks", "ticket", "tomato", "travel", "turkey", "turtle", "twelve", "valley", "violet", "voyage",
    "waffle", "walnut", "window", "winner", "winter", "wonder", "yellow", "yogurt",
  ],
};
